baseURL = "https://GW-Rocket-Team.github.io/"
languageCode = "en-us"
title = "GW Rocket Team | Vwwoosh"
theme = "navigator-hugo"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Interests"
        url     = "/interests"
        weight  = 3
    [[menu.nav]]
        name    = "Portfolio"
        url     = "/portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

    # Footer Service Menu
    [[menu.service]]
        name    = "Mechanical"
        url     = "/service"
        weight  = 1
    [[menu.service]]
        name    = "Electrical"
        url     = "/service"
        weight  = 2
    [[menu.service]]
        name    = "Software"
        url     = "/service"
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "Partners"
        url     = "/about"
        weight  = 1
    [[menu.quicklink]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.quicklink]]
        name    = "FAQ's"
        url     = "/about"
        weight  = 3
    [[menu.quicklink]]
        name    = "Awards"
        url     = "/about"
        weight  = 4

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    footerDescription = "We are The George Washington University's student-led Rocket Team. Every year, we build a rocket for the IREC competition."

    # Hero Area Section
    [params.hero]
        enable  = true
        heading = "We build things that go mach speed."
        description = "We are The George Washington University's student-led Rocket Team. Every year, we build a rocket for the IREC competition."
        button  = true
        btnText = "Learn More"
        btnURL  = "/about"
        videoThumb = "images/slider/video-player-thumb.jpg"
        videoURL   = "https://www.youtube.com/embed/2ndhYi6-gSI"

    # About 2 Section
    [params.aboutSm]
        enable  = true
        title   = "Do you wanna build a snowman?"
        description = "Come on, come out and play! I haven't seen you anymore; come out the door. It's like you've gone away."

    # Blog Section On Homepage
    [params.blog]
        enable  = true
        topTitle= "OUR STORY"
        title   = "Blog."
        subtitle= "See what we've been up to!"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Let's Create Something Together"
        subtitle= "Interested in rocketry or just looking for a way to apply your skills?"
        btnText = "Contact Us"

    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        subtitle= "We are always looking for more students to join our team!"
        address = "800 22nd St NW <br> Washington, DC 20052"
        phone   = "(202) 867 5309"
        fax     = ""
        facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/"
        linkedin= ""
        dribbble= ""
        instagram= "https://www.instagram.com/"
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"
